sudo: false
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script: travis_wait 360 mvn -B test -U -e
cache:
  directories:
    - '$HOME/.m2/repository'
before_deploy:
  - gpg --import .travis.key.gpg
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}
deploy:
  provider: script
  skip_cleanup: true
  script: mvn clean deploy -e -P release --settings .travis.settings.xml
  on:
    tags: true