sudo: false
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script: travis_wait 360 mvn -B test -U -e
cache:
  directories:
  - "$HOME/.m2/repository"
before_deploy:
- gpg --import .travis.key.gpg
- mvn versions:set -DnewVersion=${TRAVIS_TAG}
- cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    tags: true
env:
  global:
  - secure: VMHR3jdZI9gjk+IPbMIwJiC7RzL8zDyYG45e1Yb+F+nJcBD5fBC40Cah5vOeRMEcY2AmMkdXz2Zs2SZ5kTOkkXA5O6lTgTUWihVNhKsqBp5ZENWQa2cmtqcZ4IANzfMQUYS27XGZ5bYbEmRbqb7MHYH9+aNNEEbcfEcSDesW548F3fANOFQxEB/HEcU6y5Ruh5WwSZWK9jOilYZ7uhemKCUnGlTZ4SuFR0G694M0nU86QsF8M+noSF26Wsy9luDalZJ9jNoKDb98G522JOxI2i2wQEXE7N1VQbsfYlgFFg8FCIKFQ+W/ylAE0qfN17EU5CuI+nQKBKf6PFgdLp0GxtpJr6/j7i9nTf1zPS8lZZeX+N19+ZDu8FeMzo2DmhInV9VopcCD9ICJYHoQzgD24mypM1HOs47S0L4nzrKA3tWq3kEBilypFY4nHOB5atFc41wvKwsC1/zB3GkkfVgUf07sGuUpwomfgggIAZy+jt+rc1Pnj3xai/SKYj01W8d6b0Hr/WunWOXgT+JLGup/L4rVer6U+SXou9RGuNGkW0/GBW/Lc2zfKr57acpF9KGEXYxck4OcDGMAsmCxplbZ/kbU7/16M/5VJXw8UWUl6Su3IhnxroA4NRHVAGWVNQCc6mDfaBGMr7SrtWMCRu0mbnI1w3H4esPUhSaznYdD6HE=
  - secure: NUFvb1zcstakSeFQ61KAT78ilB1I5wJx/8V4Hpnk0MlAiqE8iX2/3Xh5+xFAisTBZhoKEE+hvJx1XhuEXCncDYYYHNYlVSWrSG9hzrDzQWuVCz4pJYjAN0039YAGqhhHzjQY3AlBbdc2GrESPistNjsMBnJexQ6yRb3XbAVhckvaQGQqxB6+1SskFcTEfcdfmlIpYxR1vdMmFZGWmGrfJtKKSKIxn+86sWo7iskH0RiUc3uQAUKhVjg0JM+Q8JBiEwWPSpnkwvJND7I8XVqZkMgvuJQH/Dn+KzrDkkronmoUK0y+6Ee2JrM+v3H2OdCVaJRJQnx2c3xnzgSUtGwfOqdQFw+W+kiKcbw24MAdLgFcrMmp2WGYOV2Km8fmY+ZOh7B9nQIIXDnWLsvwwf4Zdt1+Tbfp8y277TSdhqeEkuP/GV/EL/ARVc14iBs2I2856+Pr358uZcwTQ2Bwx6eZI32UzuFEzKImbpoISDhKxRdvBKCHMxDx+3v4XaLKyOpOWZb46IAcM+Bh+z9RUqEnkTANPPJ2DHqhQjkr0oFvbfYU+BjwJz4h+BUiVe1EhyLJYxpwJb1PPiHJ0CvvbcTEHgTNg1Zqf3N//FghwtjGF0q++kIggJ+hpGPyFra30RJWpdhuXnuLO39whoMNrBLZxtBCKyYNEpUoG5AshCe8KeU=
  - secure: TjZFyA1o2EC8hd8dVjDvylsR5CStZDEk+KtyN7Se/ALw4j3evGKQprZRGP9p+adumwbBaZ/wled/ncDLZitZA5iY1QOApGUZblVjC2kJK88zzeAH09JDuZuTksnBNPGdfbLw+rduWkbskL6a5DN3cvvrymiyOZDBAmwk25f+qxkAnukDUUxUPTvEtNuJitmL4a87bhtX1OAdBpnT9YfuYW8AdJARgjyA1azl4bKSl/iUiY4IW9n+3e//PqpwkIs4i7D9J4Ve8v3ArJ0lzMOvHAWiqKrz6EjJNkJrQBq8Yfb8gMDUcf7rj8ShSEzpMrhGeyywdgU6eySbIIWZUZsDaHLBtt+WUqORBVIY9DfklxiyHAgXnHbeUkR992bOFNNCFU962In4ldVul3V/fWDNS/TUj4ezkP3cq8bGaZgDlXdsS8VxZN+7Ag0ItTh5EX9PikP0XkmZQqkau64/2b1SIbdE7vXo29cGN0+L/8T7dRh0vlUlypjopEjKm6cE9VRdNm1HlmbvQBObiF4RzWJnp8aalSmcCGOH9ys/ACwfhJ48BuaowkOROkcqiHIJF688hGE/pX2XjePSOb7jONz0bxGmr8ixEn/oLLDybd1bS9nQaGhecP+SuniE31omOGKWw+NkTfEPWyNVI8IN+ztvXDm/4ReiQox9CQli09ktUTI=
